-- Seed data generated from data.js

insert into cars (name, name_en, grade, grade_en, type, maker, maker_en, year, km, price, fuel, fuel_en, trans, trans_en, drive, drive_en, seats, color, color_en, engine, engine_en, shaken, shaken_en, repair, repair_en, score, status, export, comment, comment_en, safety, safety_en, comfort, comfort_en, navi, navi_en, other, other_en) values
('ハイエース バン', 'Hiace Van', 'DX GL パッケージ 標準ボディ', 'DX GL Package, Standard Body', 'KDH201V', 'トヨタ', 'Toyota', 2019, 8.2, 189, 'ディーゼル', 'Diesel', '6速AT', '6-speed AT', 'FR（後輪駆動）', 'FR (Rear-wheel drive)', 3, 'ホワイトパールクリスタルシャイン', 'White Pearl Crystal Shine', '2KD-FTV（2,500cc ディーゼルターボ）', '2KD-FTV (2,500cc Diesel Turbo)', '2026年3月', 'March 2026', 'なし', 'None', '4（JU）', 'available', true, '走行距離少なめの高年式ハイエースです。ディーゼルエンジンで輸出先でも燃料調達が容易。車検残あり、修復歴なし。内外装ともにコンディション良好です。輸出向けとして強くお勧めできる一台です。', 'A recent-model Hiace with low mileage. The diesel engine makes fuel easy to source at export destinations. Shaken remaining, no accident history. Excellent condition inside and out — highly recommended for export.', 'VSC / ABS / エアバッグ×2', 'VSC / ABS / 2 Airbags', 'エアコン / パワーウィンドウ / キーレス', 'A/C / Power Windows / Keyless Entry', '純正SDナビ / バックカメラ', 'OEM SD Navigation / Rear Camera', 'ETC / フロアマット / ドアバイザー', 'ETC / Floor Mats / Door Visors'),
('ランドクルーザー プラド', 'Land Cruiser Prado', 'TX Lパッケージ 4WD', 'TX L Package, 4WD', 'GRJ150W', 'トヨタ', 'Toyota', 2018, 6.1, 348, 'ガソリン', 'Gasoline', '6速AT', '6-speed AT', '4WD', '4WD', 8, 'パールホワイト', 'Pearl White', '1GR-FE（4,000cc V6）', '1GR-FE (4,000cc V6)', '2026年8月', 'August 2026', 'なし', 'None', '4.5（JU）', 'available', true, '人気のGRJ150系プラドです。1GR-FEエンジン搭載の4.0L V6モデル。走行少なく状態良好。アフリカ・中東市場向けに強い一台です。', 'A popular GRJ150-series Prado with the 4.0L V6 1GR-FE engine. Low mileage, good condition. A strong choice for African and Middle Eastern markets.', 'VSC / ABS / エアバッグ×6 / クルーズコントロール', 'VSC / ABS / 6 Airbags / Cruise Control', '本革シート / ムーンルーフ / パワーシート', 'Leather Seats / Moonroof / Power Seats', '純正大型ナビ / バックカメラ / ETC', 'OEM Large Navigation / Rear Camera / ETC', 'ルーフレール / サンシェード / フロアマット', 'Roof Rails / Sunshade / Floor Mats'),
('ランドクルーザー プラド', 'Land Cruiser Prado', 'TX 4WD 走行22万km', 'TX 4WD, 224,000km', 'GRJ150W', 'トヨタ', 'Toyota', 2014, 22.4, 138, 'ガソリン', 'Gasoline', '5速AT', '5-speed AT', '4WD', '4WD', 7, 'シルバーメタリック', 'Silver Metallic', '1GR-FE（4,000cc V6）', '1GR-FE (4,000cc V6)', '2025年11月', 'November 2025', 'なし', 'None', '3.5（JU）', 'available', true, '走行22万kmですが修復歴なし。アフリカ市場では高走行の本機種でも需要があります。価格帯が手頃でコストパフォーマンスに優れます。', '224,000km on the odometer but no accident history. High-mileage units of this model remain in demand in African markets. Great value for the price.', 'VSC / ABS / エアバッグ×6', 'VSC / ABS / 6 Airbags', 'エアコン / パワーウィンドウ', 'A/C / Power Windows', '社外ナビ / バックカメラ', 'Aftermarket Navigation / Rear Camera', 'ETC / フロアマット', 'ETC / Floor Mats'),
('アルファード', 'Alphard', '2.5S Cパッケージ', '2.5S C Package', 'AGH30W', 'トヨタ', 'Toyota', 2020, 4.5, 420, 'ガソリン', 'Gasoline', 'CVT', 'CVT', '2WD', '2WD', 7, 'プレシャスホワイトパール', 'Precious White Pearl', '2AR-FE（2,500cc）', '2AR-FE (2,500cc)', '2026年5月', 'May 2026', 'なし', 'None', '4.5（JU）', 'reserved', false, '現在商談中です。キャンセル待ちのご登録も承ります。', 'Currently under negotiation. We can add you to a waiting list in case the deal falls through.', 'プリクラッシュセーフティ / LTA / ABS', 'Pre-Collision Safety / LTA / ABS', '本革シート / 電動スライドドア / 後席モニター', 'Leather Seats / Power Sliding Doors / Rear Monitor', 'T-Connect SDナビ / JBLサウンド / ETC2.0', 'T-Connect SD Navigation / JBL Sound / ETC 2.0', 'サンルーフ / デジタルインナーミラー', 'Sunroof / Digital Rearview Mirror'),
('プリウス', 'Prius', 'S 1.8L ハイブリッド', 'S 1.8L Hybrid', 'ZVW30', 'トヨタ', 'Toyota', 2017, 11.3, 98, 'ハイブリッド', 'Hybrid', 'CVT', 'CVT', '2WD', '2WD', 5, 'ブルーメタリック', 'Blue Metallic', '2ZR-FXE（1,800cc HV）', '2ZR-FXE (1,800cc Hybrid)', '2025年10月', 'October 2025', 'なし', 'None', '3.5（JU）', 'available', false, '低燃費ハイブリッド。国内向け。燃費 26.4km/L（JC08）。', 'Fuel-efficient hybrid, for domestic sale. Fuel economy 26.4km/L (JC08 mode).', 'ABS / エアバッグ×8', 'ABS / 8 Airbags', 'オートエアコン / パワーウィンドウ', 'Auto A/C / Power Windows', '純正ナビ / バックカメラ', 'OEM Navigation / Rear Camera', 'ETC / フロアマット', 'ETC / Floor Mats'),
('ノア', 'Noah', 'Si W×B III 7人乗り', 'Si W×B III, 7-Seater', 'ZRR80W', 'トヨタ', 'Toyota', 2021, 3.8, 265, 'ガソリン', 'Gasoline', 'CVT', 'CVT', '2WD', '2WD', 7, 'ホワイトパールクリスタルシャイン', 'White Pearl Crystal Shine', '3ZR-FAE（2,000cc）', '3ZR-FAE (2,000cc)', '2026年10月', 'October 2026', 'なし', 'None', '4.5（JU）', 'available', false, '最終型ノア。走行少なく状態極めて良好。車検たっぷり残。国内で高い人気を誇る一台です。', 'Final-generation Noah. Low mileage and excellent condition, with plenty of shaken remaining. Highly popular in the domestic market.', 'トヨタセーフティセンス / ABS', 'Toyota Safety Sense / ABS', '両側電動スライドドア / 本革調シート', 'Dual Power Sliding Doors / Leather-style Seats', '純正SDナビ / バックカメラ / ETC2.0', 'OEM SD Navigation / Rear Camera / ETC 2.0', 'スポーツフロントフェイス / 専用18インチアルミ', 'Sport Front Fascia / Dedicated 18" Alloys'),
('ハイエース バン', 'Hiace Van', 'スーパーGL ダークプライム', 'Super GL Dark Prime', 'GDH201V', 'トヨタ', 'Toyota', 2022, 2.1, 368, 'ディーゼル', 'Diesel', '6速AT', '6-speed AT', '2WD', '2WD', 2, 'ブラックマイカ', 'Black Mica', '1GD-FTV（2,800cc ディーゼルターボ）', '1GD-FTV (2,800cc Diesel Turbo)', '2027年1月', 'January 2027', 'なし', 'None', '5（JU）', 'available', true, '新型GDH系ハイエース。走行2万kmの極上個体。1GD-FTVエンジン搭載でパワーも燃費も向上。車検2年以上残。輸出最高評価の一台です。', 'Latest-generation GDH-series Hiace in superb condition with just 20,000km. The 1GD-FTV engine improves both power and fuel economy. Over two years of shaken remaining — our top-rated export vehicle.', 'プリクラッシュセーフティ / LDA / ABS', 'Pre-Collision Safety / LDA / ABS', '本革調シート / オートエアコン / スマートキー', 'Leather-style Seats / Auto A/C / Smart Key', '純正ディスプレイオーディオ / バックカメラ / ETC2.0', 'OEM Display Audio / Rear Camera / ETC 2.0', '専用フロントスポイラー / アルミホイール', 'Dedicated Front Spoiler / Alloy Wheels'),
('プロボックス', 'Probox', 'DX 1.5L', 'DX 1.5L', 'NCP51V', 'トヨタ', 'Toyota', 2016, 18.7, 55, 'ガソリン', 'Gasoline', '4速AT', '4-speed AT', '2WD', '2WD', 5, 'ホワイト', 'White', '1NZ-FE（1,500cc）', '1NZ-FE (1,500cc)', '—', '—', 'なし', 'None', '3（JU）', 'sold', false, '売約済みです。', 'This vehicle has been sold.', 'ABS', 'ABS', 'エアコン / パワーウィンドウ', 'A/C / Power Windows', '社外ナビ', 'Aftermarket Navigation', 'フロアマット', 'Floor Mats'),
('ランドクルーザー 200', 'Land Cruiser 200', 'ZX 4WD フルオプション', 'ZX 4WD, Fully Loaded', 'URJ202W', 'トヨタ', 'Toyota', 2019, 5.5, 680, 'ディーゼル', 'Diesel', '6速AT', '6-speed AT', '4WD', '4WD', 8, 'プレシャスホワイトパール', 'Precious White Pearl', '1VD-FTV（4,500cc V8 ディーゼル）', '1VD-FTV (4,500cc V8 Diesel)', '2026年6月', 'June 2026', 'なし', 'None', '4.5（JU）', 'available', true, '希少な1VD-FTV搭載のランクル200。フルオプション仕様。アフリカ・中東市場で高い評価が期待できます。修復歴なし、状態極上。', 'A rare Land Cruiser 200 with the 1VD-FTV engine, fully loaded. Expected to command strong value in African and Middle Eastern markets. No accident history, superb condition.', '全方位プリクラッシュ / LDA / RSA / ABS', '360° Pre-Collision / LDA / RSA / ABS', '本革シート / 後席エンタメ / クールボックス', 'Leather Seats / Rear Entertainment / Cool Box', '純正大型ナビ / 全周囲カメラ / ETC2.0', 'OEM Large Navigation / 360° Camera / ETC 2.0', 'KDSS / Multi-Terrain Select / デフロック', 'KDSS / Multi-Terrain Select / Diff Lock'),
('ヴィッツ', 'Vitz', 'F 1.0L', 'F 1.0L', 'KSP90', 'トヨタ', 'Toyota', 2018, 7.2, 68, 'ガソリン', 'Gasoline', 'CVT', 'CVT', '2WD', '2WD', 5, 'レッドマイカメタリック', 'Red Mica Metallic', '1KR-FE（1,000cc）', '1KR-FE (1,000cc)', '2026年2月', 'February 2026', 'なし', 'None', '3.5（JU）', 'available', false, '低走行の1オーナー車。日常使いに最適。燃費良好です。', 'Low-mileage, one-owner vehicle. Ideal for daily use with good fuel economy.', 'ABS / エアバッグ×4', 'ABS / 4 Airbags', 'オートエアコン / パワーウィンドウ', 'Auto A/C / Power Windows', '社外ナビ', 'Aftermarket Navigation', 'フロアマット / ドアバイザー', 'Floor Mats / Door Visors'),
('ノア ハイブリッド', 'Noah Hybrid', 'G 1.8HV 8人乗り', 'G 1.8HV, 8-Seater', 'ZWR80G', 'トヨタ', 'Toyota', 2020, 6.4, 248, 'ハイブリッド', 'Hybrid', 'CVT', 'CVT', '2WD', '2WD', 8, 'パールホワイト', 'Pearl White', '2ZR-FXE（1,800cc HV）', '2ZR-FXE (1,800cc Hybrid)', '2026年4月', 'April 2026', 'なし', 'None', '4（JU）', 'available', false, 'ハイブリッド8人乗りのノア。低燃費で維持費も安く、ファミリーユースに最適。走行少なく状態良好です。', 'An 8-seater hybrid Noah. Low running costs and great fuel economy, ideal for family use. Low mileage and good condition.', 'トヨタセーフティセンス / ABS', 'Toyota Safety Sense / ABS', '両側電動スライドドア / オートエアコン', 'Dual Power Sliding Doors / Auto A/C', '純正ナビ / バックカメラ / ETC', 'OEM Navigation / Rear Camera / ETC', 'フリップダウンモニター / フロアマット', 'Flip-down Monitor / Floor Mats'),
('ランクル プラド', 'Land Cruiser Prado', 'TZ-G ディーゼル 4WD', 'TZ-G Diesel 4WD', 'GDJ150W', 'トヨタ', 'Toyota', 2022, 1.8, 498, 'ディーゼル', 'Diesel', '6速AT', '6-speed AT', '4WD', '4WD', 7, 'アティチュードブラックマイカ', 'Attitude Black Mica', '1GD-FTV（2,800cc ディーゼルターボ）', '1GD-FTV (2,800cc Diesel Turbo)', '2027年3月', 'March 2027', 'なし', 'None', '5（JU）', 'available', true, '新型GDJ150系ディーゼルプラドの最高グレードTZ-G。走行1.8万kmの極上個体。世界中で需要の高い組み合わせで、今後入庫が難しくなるモデルです。', 'The top-grade TZ-G of the latest GDJ150-series diesel Prado. Superb condition with just 18,000km. A highly sought-after combination worldwide, and increasingly hard to source going forward.', '全方位プリクラッシュ / LDA / BSM / ABS', '360° Pre-Collision / LDA / BSM / ABS', '本革シート / ベンチレーション / ムーンルーフ', 'Leather Seats / Ventilated Seats / Moonroof', '大型ディスプレイナビ / 全周囲カメラ / ETC2.0', 'Large Display Navigation / 360° Camera / ETC 2.0', 'KDSS / Multi-Terrain Select / ルーフレール', 'KDSS / Multi-Terrain Select / Roof Rails');

insert into parts (name, name_en, cat, cat_label, cat_label_en, fit, fit_en, part_no, price, condition, stock, description, description_en) values
('エンジンASSY 2KD-FTV', 'Engine Assembly 2KD-FTV', 'engine', 'エンジン関連', 'Engine', 'ハイエース 200系（2013-2019）', 'Hiace 200 Series (2013-2019)', '19000-30D50', 185000, 'used', 2, '走行8万km時取り外し。始動良好、圧縮圧力正常。実働確認済みです。取り外し時の写真もご用意可能です。', 'Removed at 80,000km. Starts well, normal compression, tested running. Removal photos available on request.'),
('オルタネーター', 'Alternator', 'electrical', '電装品', 'Electrical', 'プリウス ZVW30系', 'Prius ZVW30 Series', '27060-37160', 12000, 'refurb', 5, 'リビルト品。6ヶ月保証付き。発電量テスト済みです。', 'Refurbished. 6-month warranty. Output tested.'),
('フロントバンパー', 'Front Bumper', 'body', '外装・ボディ', 'Body/Exterior', 'ランドクルーザー プラド 150系（前期）', 'Land Cruiser Prado 150 Series (early)', '52119-60934', 28000, 'used', 1, '小傷ありだが割れ・歪みなし。色：ホワイトパールクリスタルシャイン。', 'Minor scratches, no cracks or warping. Color: White Pearl Crystal Shine.'),
('純正アルミホイール 18インチ 4本セット', 'OEM Alloy Wheels 18" (Set of 4)', 'wheel', 'ホイール・タイヤ', 'Wheels/Tires', 'ランドクルーザー 200系', 'Land Cruiser 200 Series', '—', 68000, 'used', 1, '4本セット。タイヤ溝残り約60%。センターキャップ付属。', 'Set of 4. Tire tread approx. 60% remaining. Center caps included.'),
('ヘッドライト（左右セット）', 'Headlights (Left & Right Set)', 'electrical', '電装品', 'Electrical', 'アルファード AGH30系', 'Alphard AGH30 Series', '81145-58560', 42000, 'used', 2, 'LEDタイプ。点灯確認済み、レンズクラックなし。左右セット価格です。', 'LED type. Tested working, no lens cracks. Price is for the set.'),
('ショックアブソーバー（フロント）', 'Shock Absorber (Front)', 'suspension', '足回り', 'Suspension', 'ハイエース 200系 全般', 'Hiace 200 Series (all)', '48510-29835', 9800, 'new', 8, '新品社外品。左右1本ずつの価格です。', 'New aftermarket. Price is per single unit.'),
('リアシート一式', 'Rear Seat Set', 'interior', '内装', 'Interior', 'ノア ZRR80系', 'Noah ZRR80 Series', '—', 35000, 'used', 1, 'ファブリック地、破れ・シミなし。7人乗り3列目含みます。', 'Fabric upholstery, no tears or stains. Includes 3rd row (7-seater).'),
('ラジエーター', 'Radiator', 'engine', 'エンジン関連', 'Engine', 'ヴィッツ KSP90系', 'Vitz KSP90 Series', '16400-21200', 8500, 'refurb', 4, 'リビルト品。圧力テスト済み、水漏れなしです。', 'Refurbished. Pressure tested, no leaks.'),
('ドアミラー（右）', 'Door Mirror (Right)', 'electrical', '電装品', 'Electrical', 'プロボックス NCP51系', 'Probox NCP51 Series', '87910-52660', 4500, 'used', 3, '電動格納式。ウィンカー内蔵、動作確認済みです。', 'Power-folding type. Built-in turn signal, tested working.'),
('マフラー（純正）', 'Muffler (OEM)', 'engine', 'エンジン関連', 'Engine', 'ランクル プラド 150系（ディーゼル）', 'Land Cruiser Prado 150 Series (Diesel)', '17410-30E10', 22000, 'used', 1, '腐食少なめ。取り付け金具付属です。', 'Minimal corrosion. Mounting brackets included.'),
('テールランプ（左右セット）', 'Tail Lights (Left & Right Set)', 'body', '外装・ボディ', 'Body/Exterior', 'ハイエース 200系（後期）', 'Hiace 200 Series (late)', '81551-26580', 15000, 'new', 6, '社外新品LEDテール。左右セット。防水パッキン付属です。', 'New aftermarket LED tail lights. Set of 2. Waterproof gasket included.'),
('バッテリー 80D26L', 'Battery 80D26L', 'electrical', '電装品', 'Electrical', '汎用（多くのトヨタ車に適合）', 'Universal (fits many Toyota models)', '80D26L', 9800, 'new', 12, '新品バッテリー。1年保証付きです。', 'New battery. 1-year warranty included.');
